services:
  app:
    container_name: chunker-app
    build:
      context: .
      dockerfile: Dockerfile
    image: chunker:alpha
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      AZURE_API_KEY: ${AZURE_API_KEY}
      AI_SEARCH_INDEX_ENDPOINT: ${AI_SEARCH_INDEX_ENDPOINT}
      AI_SEARCH_INDEX_NAME: ${AI_SEARCH_INDEX_NAME}
      PYTHONUNBUFFERED: 1
    command: python3 main.py
